<?php 

	/*Ideal layout*/
	if (stripos($_SERVER[ ' REQUEST_URI ' ],  ' about' ) !== false) {echo  ' Call today or complete a free online insurance quote from to request a free insurance quote or financial planning quote from  '  . $area .  '  Insurance experts at  '  . $businessName .  '  located in  '  . $city .   ' , '  . $state;}
	if (stripos($_SERVER[ ' REQUEST_URI' ],'auto' ) || stripos($_SERVER['REQUEST_URI'],'vehicle') !== false) {echo  ' Get a free auto insurance rate quote from  '  . $businessName .  '  with an online rate quote or by calling us today ' ;}
	if (stripos($_SERVER[ ' REQUEST_URI' ],'business' ) !== false) {echo  ' Contact the business insurance experts at  '  . $businessName .  '  in  '  . $city .   ' , '  . $state .  '  for your free business insurance, commercial auto insurance, commercial property insurance, farm insurance and small business insurance quote today ' ;}
	if (stripos($_SERVER[ ' REQUEST_URI' ],'calculators' ) !== false) {echo $businessName .  '  provides financial calculators to assist in assessing your financial planning and insurance needs. Call today to speak with one of your experience financial planners and insurance agents ' ;}
	if (stripos($_SERVER[ ' REQUEST_URI' ],'carriers' ) !== false) {echo $businessName .  '  is an independent insurance agency that works with a variety of carriers so they can better serve the insurance needs of  '  . $area ;}
	if (stripos($_SERVER[ ' REQUEST_URI' ],'claims' ) !== false) {echo $businessName .  '  handles all auto insurance claims, business insurance claims, life insurance claims, and property insurance claims with care. Call today to file your claim with  '  . $businessName;}
	if (stripos($_SERVER[ ' REQUEST_URI' ],'contact' ) !== false) {echo  ' Contact Us today- Call or complete a free online insurance quote form to request a free insurance quote or financial planning quote from  '  . $area .  '  Insurance experts at  '  . $businessName .  '  located in  '  . $city .   ' , '  . $state .  ' . ' ;}
	if (stripos($_SERVER[ ' REQUEST_URI' ],'coverage' ) !== false) {echo  ' The independent insurance agents at  '  . $businessName .  '  service the State of  '  . $state .  ' with an emphasis on the insurance needs of  '  . $counties;}
	if (stripos($_SERVER[ ' REQUEST_URI' ],'glossary' ) !== false) {echo $businessName .  '  provides an Insurance Glossary of terms with helpful insurance industry information to better serve our insurance customers, call   '  . $businessName .  '   today ' ;}
	if (stripos($_SERVER[ ' REQUEST_URI' ],'health' ) !== false) {echo  ' Contact the personal insurance agents at   '  . $businessName .  '  , a trusted choice agency in  '  . $city .   ' , '  . $state .  '  for your free life insurance, health insurance, and financial planning quote or consultation ' ;}
	if (stripos($_SERVER[ ' REQUEST_URI' ],'home' ) !== false) {echo  ' Get your free property insurance quote, rental insurance quote, homeowner insurance quote, flood insurance quote, or mobile home insurance quote from  '  . $businessName .  '  in  '  . $city .   ' , '  . $state ;}
	if (stripos($_SERVER[ ' REQUEST_URI' ],'index' ) !== false) {echo  ' Call today to request a free insurance quote from  '  . $businessName .  '  located in  '  . $city .   ' , '  . $state ;}
	if (stripos($_SERVER[ ' REQUEST_URI' ],'life' ) !== false) {echo  ' Contact the personal insurance agents at   '  . $businessName .  '  , a trusted choice agency in  '  . $city .   ' , '  . $state .  '  for your free life insurance, health insurance, and financial planning quote or consultation ' ;}
	if (stripos($_SERVER[ ' REQUEST_URI' ],'links' ) !== false) {echo  ' Contact the insurance experts at  '  . $businessName .  '  in  '  . $city .   ' , '  . $state .  '  to discuss your financial planning needs, auto insurance, property insurance, business insurance and personal insurance coverage. ' ;}
	if (stripos($_SERVER[ ' REQUEST_URI' ],'property' ) !== false) {echo  ' Get your free property insurance quote, rental insurance quote, homeowner insurance quote, flood insurance quote, or mobile home insurance quote from  '  . $businessName .  '  in  '  . $city .   ' , '  . $state ;}
	if (stripos($_SERVER[ ' REQUEST_URI' ],'quote' ) !== false) {echo  ' Contact the independent insurance agents at  '  . $businessName .  '  for your free auto insurance, free life insurance quote, free health insurance quote, free business insurance quote or free property insurance quote ' ;}
	if (stripos($_SERVER[ ' REQUEST_URI' ],'resources' ) !== false) {echo $businessName .  '  in  '  . $city .   ' , '  . $state .  '  provides insurance resources for all auto insurance, property insurance, business insurance and personal insurance customers with an insurance glossary of terms, helpful insurance links, and insurance rate calculators ' ;}
	if (stripos($_SERVER[ ' REQUEST_URI' ],'services' ) !== false) {echo  ' Contact the independent insurance agents at  '  . $businessName .  '  for your free auto insurance, free life insurance quote, free health insurance quote, free business insurance quote or free property insurance quote ' ;}

else {echo  ' Contact the independent insurance agents at  '  . $businessName .  '  for your free auto insurance, free life insurance quote, free health insurance quote, free business insurance quote or free property insurance quote ' ;}
	?>