<?php include("data.php"); ?>
<?php 	//Set Page Specific Vars Here 
        //$generalTitle="";
        //$formEmail="";
        $pagePhoto="banner_homeOwners_insurance.jpg";
        $pagePhotoAlt="homeowners insurance in $stateName";
?>
<?php include("header.php"); ?>
<?PHP include ("sidebar.php");?>

<div id="bodytext" class="column">
     <h1>Property Insurance</h1>
        
    <p><b>What is homeowners insurance? <br /></b>Homeowners insurance provides financial protection against disasters. A standard policy insures the home itself and the things you keep in it.</font></p>
    <p>Homeowners insurance is a package policy. This means that it covers both damage to your property and your liability or legal responsibility for any injuries and property damage you or members of your family cause to other people. This includes damage caused by household pets.</font></p>
    <p>Damage caused by most disasters is covered but there are exceptions. The most significant are damage caused by floods, earthquakes and poor maintenance. You must buy two separate policies for flood and earthquake coverage. Maintenance-related problems are the homeowners' responsibility.</font></p>
    <p><b>What is in a standard homeowners insurance policy? <br /></b>A standard homeowners insurance policy includes four essential types of coverage. They include:<br />1.&nbsp;Coverage for the structure of your home.<br />2.&nbsp;Coverage for your personal belongings.<br />3.&nbsp;Liability protection.<br />4.&nbsp;Additional living expenses in the event you are temporarily unable to live in your home because of a fire or other insured disaster.</font></p>
    <p><b>1. The structure of your house<br /></b>This part of your policy pays to repair or rebuild your home if it is damaged or destroyed by fire, hurricane, hail, lightning or other disaster listed in your policy. It will not pay for damage caused by a flood, earthquake or routine wear and tear. When purchasing coverage for the structure of your home, it is important to buy enough to rebuild your home.</font></p>
    <p>Most standard policies also cover structures that are detached from your home such as a garage, tool shed or gazebo. Generally, these structures are covered for about 10% of the amount of insurance you have on the structure of your home. If you need more coverage, talk to your insurance agent about purchasing more insurance.<br />&nbsp;&nbsp;&nbsp; <br /><b>2. Your personal belongings<br /></b>Your furniture, clothes, sports equipment and other personal items are covered if they are stolen or destroyed by fire, hurricane or other insured disaster. Most companies provide coverage for 50% to 70% of the amount of insurance you have on the structure of your home. So if you have $100,000 worth of insurance on the structure of your home, you would have between $50,000 to $70,000 worth of coverage for your belongings. The best way to determine if this is enough coverage is to conduct a home inventory.</font></p>
    <p>This part of your policy includes off-premises coverage. This means that your belongings are covered anywhere in the world, unless you have decided against off-premises coverage. Some companies limit the amount to 10% of the amount of insurance you have for your possessions. </font></p>
    <p>Expensive items like jewelry, furs and silverware are covered, but there are usually dollar limits if they are stolen. Generally, you are covered for between $1,000 to $2,000 for all of your jewelry and furs. To insure these items to their full value, purchase a special personal property endorsement or floater and insure the item for its appraised value. Coverage includes &ldquo;accidental disappearance,&rdquo; meaning coverage if you simply lose that item. And there is no deductible.</font></p>
    <p>Trees, plants and shrubs are also covered under standard homeowners insurance. Generally you are covered for 5% of the insurance on the house&mdash;up to about $500 per item. Perils covered are theft, fire, lightning, explosion, vandalism, riot and even falling aircraft. They are not covered for damage by wind or disease.</font></p>
    <p><b>3. Liability protection<br /></b>Liability covers you against lawsuits for bodily injury or property damage that you or family members cause to other people. It also pays for damage caused by your pets. So, if your son, daughter or dog accidentally ruins your neighbor&rsquo;s expensive rug, you are covered. However, if they destroy your rug, you are not covered.</font></p>
    <p>The liability portion of your policy pays for both the cost of defending you in court and any court awards&mdash;up to the limit of your policy. You are also covered not just in your home, but anywhere in the world.</font></p>
    <p>Liability limits generally start at about $100,000. However, experts recommend that you purchase at least $300,000 worth of protection. Some people feel more comfortable with even more coverage. You can purchase an umbrella or excess liability policy which provides broader coverage, including claims against you for libel and slander, as well as higher liability limits. Generally, umbrella policies cost between $200 to $350 for $1 million of additional liability protection.</font></p>
    <p>Your policy also provides no-fault medical coverage. In the event a friend or neighbor is injured in your home, he or she can simply submit medical bills to your insurance company. This way, expenses are paid without a liability claim being filed against you. You can generally get $1,000 to $5,000 worth of this coverage. It does not, however, pay the medical bills for your family or your pet.</font></p>
    <p><b>4. Additional living expenses<br /></b>This pays the additional costs of living away from home if you can't live there due to damage from a fire, storm or other insured disaster. It covers hotel bills, restaurant meals and other living expenses incurred while your home is being rebuilt. Coverage for additional living expenses differs from company to company. Many policies provide coverage for about 20% of the insurance on your house. You can increase this coverage, however, for an additional premium. Some companies sell a policy that provides an unlimited amount of loss-of-use coverage, but for a limited amount of time.&nbsp; If you rent out part of your house, this coverage also reimburses you for the rent that you would have collected from your tenant if your home had not been destroyed.&nbsp;&nbsp;&nbsp; </font></p>
    <p></font></p>
    <p><b>What is an umbrella liability policy? <br /></b>If you are ever sued, your standard homeowners or auto policy will provide you with some liability coverage, paying for judgments against you and your attorney's fees, up to a limit set in the policy. However, in our litigious society, you may want to have an extra layer of liability protection. That's what a personal umbrella liability policy provides.</font></p>
    <p>An umbrella policy kicks in when you reach the limit on the underlying liability coverage in a homeowners, renters, condo or auto policy. It will also cover you for things such as libel and slander.</font></p>
    <p>For about $150 to $300 per year you can buy a $1 million personal umbrella liability policy. The next million will cost about $75, and $50 for every million after that.</font></p>
    <p>Because the personal umbrella policy goes into effect after the underlying coverage is exhausted, there are certain limits that usually must be met in order to purchase this coverage. Most insurers will want you to have $250,000 or more of liability insurance on your auto policy and $300,000 of liability insurance on your homeowners policy before selling you an umbrella liability policy for $1 million of additional coverage.</font></p>
    <p>source:&nbsp; </font><a href="http://www.iii.org">http://www.iii.org</font></a></p>
    <p><b>If you would like information about other types of personal insurance, please call our agency.&nbsp; We will be glad to answer any questions you may have.</b></font></p>

</div>


<?php include("footer.php"); ?>
