<?php include("data.php"); ?>
<?php 	//Set Page Specific Vars Here 
        //$generalTitle="";
        //$formEmail="";
        $pagePhoto="banner_commercial_farmnranch_insurance.jpg";
        $pagePhotoAlt="Farm and Ranch Insurance in $area";
?>
<?php include("header.php"); ?>
<?PHP include ("sidebar.php");?>

<div id="bodytext" class="column">
<h1>Causes of Loss</h1>

<h3>Types of crop losses</h3>

<p><b>Production losses</b> - Diseases, insects, weeds and other pests annually cause substantial losses in the yield and quality of vegetables produced in Canada. Reliable estimates of these losses are not available, but they probably are proportional to losses in the USA. Even with the extensive application of pesticides, the estimated reductions in the farm-gate value of selected vegetable crops in the United States caused by diseases range from 8 to 23%, by insects 4 to 21 %, and by weeds 8 to 13%. If it is accepted that the average losses caused by diseases, insects and weeds in Canada are 15.5, 12.5 and 10.5%, respectively, they would have reduced returns to the vegetable industry by $172.7, $138.2 and $115.2 million, respectively, in 1990. If the costs of crop protection practices were factored in, these figures would be even higher. In the United States in 1987, crop losses caused by diseases and insects in specific vegetables were, respectively: cole crops 9 and 13%, lettuce 12 and 7%, potato 20 and 6%, tomato 21 and 7%, sweet corn 8 and
19%, onion 21 and 4%, cucumber 15 and 21%, pea 23 and 4%, and pepper 14 and 7%. Losses in greenhouse lettuce, cucumber and tomato are similar, but pest damage may necessitate replanting the whole crop. Until resistant cultivars of tomato became available, this was regularly the case with fusarium crown and root rot.</p>

<p><b>Post-harvest losses</b> - Reduced yield and quality from pest damage in the field may be equalled or exceeded by losses in storage. This is especially the case where freshly harvested produce is not rapidly cooled or where it is not transported and stored under controlled conditions. For example, it is not unusual to see truckloads of perishable vegetables parked on farms, at roadside truck-stops and at food terminals rapidly deteriorating in the full summer sun. Similarly, attempts to dry onions in primitive storages with humid air frequently result in wetter, not drier, onions in production areas of the Great Lakes region. Such crops are often destroyed by diseases, such as neck rot and sour skin. Poorly stored carrot, potato and cabbage crops also are subject to substantial losses.</p>

<p><b>Selected references</b><br />
Kim, S.H., L.B. Forer, and J.L. Longnecker. 1975. Recovery of plant pathogens from commercial peat-products. Proc. Am. Phytopathol. Soc. 2:124.
Pimentel, D., L. McLaughlin, A. Zepp, B. Lakitan, T. Kraus, P. Kleinman, F. Vancini, W.J. Roach, E. Graap, W.S. Keeton, and G. Selig. 1991. Environmental and economic impacts of reducing U.S. agricultural pesticide use. Pages 679–720 in D. Pimentel, ed., Handbook of Pest Management in Agriculture. Vol. 2. CRC Press, Boca Raton, Florida. 773 pp.</p>

<h3>Causes of crop losses</h3>

<p>Direct crop losses caused by diseases and pests may be measured as the proportion of crop not sold. In addition to losses in yield and quality in the field and later during storage and transport, there are many, less tangible ways in which diseases and pests exact an economic toll. For example, the fungus Botrytis cinerea may cause multiple but almost imperceptible ghost spot lesions on tomato fruit, which, depending on the rigor of official or consumer inspection, may result in little or no financial loss to the grower. However, the same fungus causing a single, girdling lesion on the stem of an indeterminate tomato cultivar will result in the total loss in yield from that plant, as often happens in the greenhouse.</p>

<p>Bacterial spot on processing tomatoes makes the skin very difficult to peel by standard factory procedures, so the skins have to be removed by hand, which is very expensive. On the other hand, buyers of fresh-market tomatoes at roadside stands may scarcely notice a few lesions of bacterial spot. Similarly, when cabbage is fermented to produce sauerkraut, or cooked, the lesions caused by thrips are very pronounced and unacceptable, whereas thrips damage may be of little consequence if the cabbage is finely chopped and used fresh in coleslaw.</p>

<p>Nematode damage to roots may be mechanical or chemical, thereby reducing root capacity to absorb and translocate water and nutrients, even when soil moisture is adequate. Some vegetable crops are tolerant of nematode damage, while others are highly sensitive. Seedlings and young transplants usually are especially susceptible. The distribution of nematodes in the soil, whether in the field or in the greenhouse, normally is uneven. Plant-parasitic nematodes may reduce crop yield and quality but other biotic and abiotic stresses on plants make it difficult to predict the impact of nematode damage. Losses may increase significantly if nematodes interact with other
pathogens, such as fungi and viruses. In Canada, yield-loss data, where available, are generally restricted to a few crops within a limited geographical area.</p>

<p>Insects and mites may damage vegetable plants directly or indirectly. For example, larvae and adults of the Colorado potato beetle may extensively defoliate a potato plant, substantially reducing its photosynthetic capacity and resulting in significant reduction in yield of tubers or even death of the plant; however, infestations that occur late in the growing season may have little effect on yield. Direct damage also may be caused by wireworms that feed or burrow into tubers, and this damage may be augmented by rot caused by bacteria and fungi. Aphids and leafhoppers suck on the foliage of the plant, reducing its vigor, but these insects also may damage a crop indirectly by transmitting plant viruses. Reduction in the yield of greenhouse- grown tomato, resulting from extensive (piercing and sucking) feeding by adults and nymphs of the greenhouse whitefly and the two-spotted spider mite, is a less direct form of damage to the crop than is the feeding on the fruit of field grown tomato by horn worms and cutworms. Consumption of foliage of cabbage plants by larvae of the cabbage looper or the imported cabbage worm reduces the vigor of the plant, resulting in a smaller head; these insects also may feed directly in the head, rendering it unmarketable, or on the outer wrapper leaves of fresh- market cabbage and cauliflower, downgrading marketability. Similarly, the presence of insects in a marketed product, such as heads of broccoli, may render the product unmarketable without visible evidence of feeding by the insect.</p>

<p>The economic significance of damage and the action threshold applied in deciding on measures to manage populations of pests depend on the severity of damage, the value of the crop, and the proposed end use of the crop. For example, the threshold approaches zero for species that cause damage directly to the part of the crop to be used by the consumer; these include the carrot rust fly in carrot and the corn borer in pepper and sweet corn. On the other hand, low populations of pests that cause foliar damage but do not feed on or damage marketable parts of the plant may be tolerated, and thus the action threshold for implementation of control procedures is higher; examples include the Colorado potato beetle on potato and the cabbage maggot on cabbage. Similarly, relatively high numbers of the two-spotted spider mite and of the greenhouse whitefly can be tolerated on greenhouse-grown cucumber and tomato without affecting the yield of marketed product significantly. Action thresholds also may vary with the stage of development of the vegetable plant when attacked. For example, low populations of the imported cabbageworm and cabbage looper can be tolerated when they feed on the foliage of young plants of cabbage, cauliflower and Brussels sprouts. Later, however, the tolerance for these pests is greatly reduced when they feed on the head or wrapper leaves of cabbage or cauliflower or in the head of broccoli. Likewise, thresholds for pests that cause indirect damage is very low if the pest can disseminate plant pathogens. For example, low populations of aphids do not cause significant loss of yield in potato, but the potential for spread of aphid-vectored viruses is so high that control measures must be considered whenever aphids appear, particularly in seed-potato crops.</p>

<p>Crop losses caused by competition from weeds can be assessed quite readily, but weeds also contribute to overall crop losses by acting as alternative hosts for pathogens and insects. For example, wild cucumber (Echinocystis lobata (Michx.) Torr. & Gray) harbors the fungus Didymella bryoniae, which causes gummy stem blight in melon and cucumber (see Greenhouse cucumber, 22.11). The universal pathogens Botrytis cinerea, Sclerotinia sclerotiorum and
S. minor are found on many weed species, B. cinerea in particular having hundreds of hosts. Weeds also may act as a reservoir for many vegetable viruses and mycoplasma-like
organisms, and of their insect and nematode vectors. The passage of workers and machinery through weed-infested crops can transmit viruses from weeds to crop plants; weed canopies provide the humid and cool microclimate in which fungi and bacteria infect their vegetable hosts; and finally, weeds provide shelter for pest insects and other types of animals, such as rabbits and rodents. Weed control, therefore, is an important part of a pest management program for vegetable crops.</p>

<p><a href="contact.php">Contact Us</a> today at <? echo $mainPhone[0];?> or visit the location nearest you, and let us find the right coverage for your farm and ranch needs. We can provide an free, exploratory <a href="insurance-quote.php">quote</a> that gives you a fast, accurate picture of rates and coverages.</p>
<p></p>


</div>


<?php include("footer.php"); ?>
